### PR TITLE
Saving User Options to NetCDF Attributes

### PR DESCRIPTION
**Pull request by garrettstaller**
Users may edit modules in the source code through option files that range from the types of forcing to presence of pipes and rivers. To make replicating runs easier, these options are now saved as attributes to the netCDF history files outputted during the run. That is, viewing a netCDF via 'ncdump -h <filename.nc>', the user will see relevant options regarding tides, pipes, rivers, surface forcing, tracking diagnostics,  and the presence of particles.

### CODE REVIEW

**Comment by nmolem** [comment]
Since this branch doesn't have the continuous integration, did you make sure that all the tests complete correctly?

**Comment by nmolem** [comment]
We will probably extend this functionality going forward as we are retiring more cpp keys. But I'll merge this with the ifx_functionality branch, which is what we're currently developing on.

**Comment by garrettstaller** [comment]
> Since this branch doesn't have the continuous integration, did you make sure that all the tests complete correctly?

Yes, running the test script in the code check directory for examples will return a series of successful tests.

**Comment by nmolem** [comment]
Please clean up the code in tides.F along the lines of our discussion and revisit the other modules for similar issues

**Comment by garrettstaller** [comment]
Code for tides.f as well as all other modules have been updated for readability and consistency. A bug was also addressed for the rivers_real example, where the new attributes were not being properly set for netcdf files. Issue related to when river forces are set for real input data in relation to when the netcdf files gain their attributes in main.f. The solution being the addition of 'call set_forces' in line 236 of main.F, specifically not within the ana_initial cpp key (line 213) - which would be ignored for real rivers - and after allocating 'time' (line 233) so maya benchmarks in code check still match.

**Comment by garrettstaller** [comment]
Changed where certain strings used in the printing of integer option settings are allocated to the subroutines in which attributes themselves are set. Also removed attribute related to surf_flux.F

**Review by nmolem — APPROVED** [review]

**Pull request merged**
